server {
    listen 80;
    server_name healora.ru www.healora.ru;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name healora.ru www.healora.ru;
    root /var/www/healora.ru;
    index index.html index.htm;
    
    ssl_certificate /etc/letsencrypt/live/healora.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/healora.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    
    location /api/ {
        proxy_pass http://127.0.0.1:3051;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /digital-twin/ {
        try_files $uri $uri/ /digital-twin/index.html;
    }
    
    location / {
        try_files $uri $uri/ =404;
    }
}